#+SEQ_TODO: OPEN | RESOLVED
#+TITLE: swankr: Bug list
#+AUTHOR: Christophe Rhodes
#+EMAIL: csr21@cantab.net
#+OPTIONS: H:0 toc:nil
* OPEN #1 printed output not redirected to slime repl                 :MINOR:
  The output from functions performing printing is sent to the
  standard output of the process running =swank()=, not to an emacs
  stream.
* OPEN #2 popping beyond inspector history crashes                   :NORMAL:
  Inspecting something and hitting =l= causes the R debugger to pop
  up from trying to send =NULL= in a sexp to Emacs.
* RESOLVED #3 source reference in compile-string-for-emacs   :WISHLIST:FIXED:
  It would be good if we could associate the expressions in the string
  with a reference to the corresponding source.  Unfortunately, emacs
  only passes the buffer position in bytes (or maybe characters),
  whereas R's srcrefs work with lines and columns.
* OPEN #4 multibyte characters corrupt slime connection              :NORMAL:
  Not in all circumstances (e.g. "£" is OK) but 1:£ fails in
  slime-net-read-or-lose.
* COMMENT:
Local Variables:
mode: org;
End:
